apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: prod
  name: predix-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: predix-web
  template:
    metadata:
      labels:
        app: predix-web
    spec:
      containers:
        - name: predix-web-container01
          env:
            - name: VITE_BASE_URL
              valueFrom:
                configMapKeyRef:
                  name: config
                  key: API_SERVER_URL
          image: pradeepkundekar0101/predix-web
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "2Gi"
              cpu: "1000m"
            limits:
              memory: "4Gi"
              cpu: "2000m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 15
            periodSeconds: 10